// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComicBook(arg1, arg2) {
  return window['go']['main']['App']['AddComicBook'](arg1, arg2);
}

export function DeleteComic(arg1) {
  return window['go']['main']['App']['DeleteComic'](arg1);
}

export function GetComicInfo() {
  return window['go']['main']['App']['GetComicInfo']();
}

export function OpenCBZFile() {
  return window['go']['main']['App']['OpenCBZFile']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
