// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComicBook(arg1, arg2) {
  return window['go']['main']['App']['AddComicBook'](arg1, arg2);
}

export function DeleteComic(arg1) {
  return window['go']['main']['App']['DeleteComic'](arg1);
}

export function GenerateULID() {
  return window['go']['main']['App']['GenerateULID']();
}

export function GetComicList() {
  return window['go']['main']['App']['GetComicList']();
}

export function GetInitialOpenedCBZ() {
  return window['go']['main']['App']['GetInitialOpenedCBZ']();
}

export function OpenCBZByID(arg1) {
  return window['go']['main']['App']['OpenCBZByID'](arg1);
}

export function OpenCBZByPath(arg1) {
  return window['go']['main']['App']['OpenCBZByPath'](arg1);
}

export function SelectAnyComic() {
  return window['go']['main']['App']['SelectAnyComic']();
}

export function SelectOnlyCBZ() {
  return window['go']['main']['App']['SelectOnlyCBZ']();
}
