// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddComicBook(arg1:string,arg2:string):Promise<string>;

export function DeleteComic(arg1:string):Promise<void>;

export function GenerateULID():Promise<string>;

export function GetComicList():Promise<Record<string, string>>;

export function GetInitialOpenedCBZ():Promise<main.ComicInfo>;

export function OpenCBZByID(arg1:string):Promise<main.ComicInfo>;

export function OpenCBZByPath(arg1:string):Promise<main.ComicInfo>;

export function SelectAnyComic():Promise<string>;

export function SelectOnlyCBZ():Promise<string>;
