// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddComicBook(arg1:string,arg2:string):Promise<main.Archive>;

export function DeleteComic(arg1:string):Promise<void>;

export function GenerateULID():Promise<string>;

export function GetComicInfo():Promise<Record<string, main.Archive>>;

export function GetInitialOpenedCBZ():Promise<number>;

export function OpenCBZFile():Promise<number>;

export function SelectFile():Promise<string>;
