// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComicBook(arg1:string,arg2:string):Promise<string>;

export function DeleteComic(arg1:string):Promise<void>;

export function GenerateULID():Promise<string>;

export function GetComicList():Promise<Record<string, string>>;

export function GetInitialOpenedCBZ():Promise<number>;

export function OpenCBZFile():Promise<number>;

export function SelectFile():Promise<string>;
