name: Release

on:
  push:
    tags: ["v*"]

env:
  APP_NAME: "cosmic-reader"
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: ""
          - goos: windows
            goarch: amd64
            suffix: ".exe"
          # - goos: darwin
          #   goarch: amd64
          #   suffix: ""
          # - goos: darwin
          #   goarch: arm64
          #   suffix: ''
          # - goos: linux
          #   goarch: arm64
          #   suffix: ''

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y libwebkit2gtk-4.1-dev

      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Setup NodeJS
        uses: actions/setup-node@v7
          with:
            node-version: 24
            package-manager-cache: false 

      - run: npm ci --prefix ./frontend
      - run: npm run build --prefix ./frontend

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          wails build -upx -trimpath -o ${APP_NAME}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/bin/${{ env.APP_NAME }}-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.suffix }}
          if-no-files-found: error
          overwrite: true
      - run: ls -R build/bin

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true
      - run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: artifacts/*
          generate_release_notes: true
